name: Test Cache
on: 
  workflow_dispatch:
   
jobs:
  prelaunch:
    runs-on: ubuntu-latest
    steps:
      - name: Create dist directory
        uses: actions/cache@v2
        with:
          path: |
            ~/dist
          key: ${{ github.run_id }}-dist
       - name: List directories
         run: "ls ~"
       - name: Create file in dist directory
         run: "touch ~/dist/boo.txt"
       
    
  compile-pico-code:
    runs-on: ubuntu-latest
    needs: prelaunch
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Reuse dist directory
        uses: actions/cache@v2
        with:
          path: |
            ~/dist
          key: ${{ github.run_id }}-dist      
      - name: List files in home directory in runner
        run: "ls ~"

          


